export const manualPreviewPresets = [
  {
    id: "KURIS_SEVEN_RWY19",
    label: "KURIS SEVEN RWY19",
    procedureId: "KURIS_SEVEN_RWY19",
    chartId: "KURIS_SEVEN",
    chartTitle: "KURIS SEVEN DEPARTURE",
    suggestedChartFilename: "KURIS_SEVEN.png",
    traceType: "APPROX_TURN",
    coordinateSpace: "anchor-normalized",
    anchorFrame: {
      originId: "CHE",
      axisToId: "KURIS",
      startId: "RJCC_RWY19_REPRESENTATIVE",
      finalId: "KURIS",
    },
    constructionDefaults: {
      stationId: "CHE",
      radialDeg: 11,
      bearingType: "MAGNETIC",
      magneticVariationDeg: -9,
      dmeNm: [2, 6],
    },
  },
  {
    id: "KURIS_SEVEN_RWY01",
    label: "KURIS SEVEN RWY01",
    procedureId: "KURIS_SEVEN_RWY01",
    chartId: "KURIS_SEVEN",
    chartTitle: "KURIS SEVEN DEPARTURE",
    suggestedChartFilename: "KURIS_SEVEN.png",
    traceType: "APPROX_TURN",
    coordinateSpace: "anchor-normalized",
    anchorFrame: {
      originId: "CHE",
      axisToId: "KURIS",
      startId: "RJCC_RWY01_REPRESENTATIVE",
      finalId: "KURIS",
    },
    constructionDefaults: {
      stationId: "CHE",
      radialDeg: 11,
      bearingType: "MAGNETIC",
      magneticVariationDeg: -9,
      dmeNm: [],
    },
  },
  {
    id: "CHITOSE_FOUR_RWY01",
    label: "CHITOSE FOUR RWY01",
    procedureId: "CHITOSE_FOUR_RWY01",
    chartId: "CHITOSE_FOUR",
    chartTitle: "CHITOSE FOUR DEPARTURE",
    suggestedChartFilename: "CHITOSE_FOUR.png",
    traceType: "APPROX_TURN",
    coordinateSpace: "anchor-normalized",
    anchorFrame: {
      originId: "CHE",
      axisToId: "CHE",
      startId: "RJCC_RWY01_REPRESENTATIVE",
      finalId: "CHE",
    },
    constructionDefaults: {
      stationId: "CHE",
      bearingType: "MAGNETIC",
      magneticVariationDeg: -9,
      dmeNm: [6.3, 10],
    },
  },
  {
    id: "CHITOSE_ONE_RWY01_TODO",
    label: "CHITOSE ONE RWY01 (TODO)",
    procedureId: "CHITOSE_ONE_RWY01",
    chartId: "CHITOSE_ONE",
    chartTitle: "CHITOSE ONE DEPARTURE",
    suggestedChartFilename: "CHITOSE_ONE.png",
    traceType: "APPROX_TURN",
    coordinateSpace: "anchor-normalized",
    enabled: false,
    notes: "TODO scaffold only: exact procedure selector id/final fix has not been added to procedures.js yet.",
    anchorFrame: {
      originId: "CHE",
      axisToId: "CHE",
      startId: "RJCC_RWY01_REPRESENTATIVE",
      finalId: "CHE",
    },
    constructionDefaults: {
      stationId: "CHE",
      bearingType: "MAGNETIC",
      magneticVariationDeg: -9,
      dmeNm: [],
    },
  },
  {
    id: "CHITOSE_ONE_RWY19_TODO",
    label: "CHITOSE ONE RWY19 (TODO)",
    procedureId: "CHITOSE_ONE_RWY19",
    chartId: "CHITOSE_ONE",
    chartTitle: "CHITOSE ONE DEPARTURE",
    suggestedChartFilename: "CHITOSE_ONE.png",
    traceType: "APPROX_TURN",
    coordinateSpace: "anchor-normalized",
    enabled: false,
    notes: "TODO scaffold only: exact procedure selector id/final fix has not been added to procedures.js yet.",
    anchorFrame: {
      originId: "CHE",
      axisToId: "CHE",
      startId: "RJCC_RWY19_REPRESENTATIVE",
      finalId: "CHE",
    },
    constructionDefaults: {
      stationId: "CHE",
      bearingType: "MAGNETIC",
      magneticVariationDeg: -9,
      dmeNm: [],
    },
  },
];

export function getManualPreviewPreset(id) {
  return manualPreviewPresets.find((preset) => preset.id === id) || null;
}
