export const LATERAL_HDG = "LATERAL_HDG";
export const LATERAL_DIRECT_FIX = "LATERAL_DIRECT_FIX";
export const LATERAL_PROCEDURE = "LATERAL_PROCEDURE";
export const LATERAL_HOLD = "LATERAL_HOLD";
export const VERTICAL_ALT_CAPTURE = "VERTICAL_ALT_CAPTURE";
export const VERTICAL_PROFILE = "VERTICAL_PROFILE";
export const SPEED_ASSIGNED = "SPEED_ASSIGNED";
export const SPEED_MANAGED = "SPEED_MANAGED";
